server:
  port: 8080

logging:
  level:
    com.chatapp: INFO

spring:
  application:
    name: chat-app

  h2:
    console:
      enabled: false
      path: /h2-console

  sql:
    init:
      mode: never

  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      uri: ${db.nosql.uri}
      auto-index-creation: true
      uuid-representation: java-legacy

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

chatapp:
  otp:
    length: 6
    expiry:
      millis: 900000
    verify:
      maxtry: 3
  chatid:
    suffix:
      length: 3
  chats:
    default:
      size: 50
  jwttoken:
    expiry:
      millis: 604800000
  cookie:
    maxage:
      seconds: 604800
  user:
    active:
      session: 3
    hardCheck:
      deviceId: false
  jwt_token:
    secret_key: ${jwt_token.secret_key}
  twilio:
    account_sid: ${twilio.account_sid}
    auth_token: ${twilio.auth_token}
    phone_number: ${twilio.phone_number}
    activate: ${twilio.activate}
